name: Build and deploy a Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://howto.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_GIT_REPO=${{ github.repository }}
            NEXT_PUBLIC_GIT_BRANCH=main

      - name: Deploy to Rancher
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.RANCHER_API_TOKEN }}" \
            'https://rancher.acdh-dev.oeaw.ac.at/v3/project/c-zdbh8:p-6vb45/workloads/deployment:howto:howto?action=redeploy'
